export default {
  GET_ACCOUNT_BALANCE: 'ACCOUNT_BALANCE',
  SET_ACCOUNT_ADDRESS: 'SET_ACCOUNT_ADDRESS',
  SET_ACCOUNT_LOADER: 'SET_ACCOUNT_LOADER',
  SET_TWITTER_DATA: 'SET_TWITTER_DATA',
  GET_TWEETS_DATA: 'GET_TWEETS_DATA',
  GET_HEADER_TITLES: 'GET_HEADER_TITLES',
  SET_CURRENT_ROUTE_TITLE: 'SET_CURRENT_ROUTE_TITLE',
  //non-actual
  GET_THEME: 'GET_THEME',
  GET_WEB3_OBJECT: 'GET_WEB3_OBJECT',
  //eth2.0 protocol
  GET_ETH2_STAKE_DATA: 'GET_ETH2_STAKE_DATA',
  GET_ETH2_STAKE_TOTAL: 'GET_ETH2_STAKE_TOTAL',
  //sushiStake LP toke (SLP) protocol
  GET_SLP_STAKE_DATA: 'GET_SLP_STAKE_DATA',
  GET_SLP_STAKE_TOTAL: 'GET_SLP_STAKE_TOTAL',
  // nftData
  SET_NFT_DATA: 'SET_NFT_DATA',
  GET_NFT_DATA: 'GET_NFT_DATA',
  INITIAL_NFT_DATA: 'INITIAL_NFT_DATA',
  //YearnFinance protocol
  SET_YFI_TOKEN_DATA: 'SET_YFI_TOKEN_DATA',
  GET_YFI_TOKEN_DATA: 'GET_YFI_TOKEN_DATA',
  GET_YFI_TOKEN_TOTAL: 'GET_YFI_TOKEN_TOTAL',
  SET_YTOKEN_DATA: 'SET_YTOKEN_DATA',
  GET_YTOKEN_DATA: 'GET_YTOKEN_DATA',
  GET_YTOKEN_TOTAL: 'GET_YTOKEN_TOTAL',

  //balancerv2LP
  SET_BALANCER_LP: 'SET_BALANCER_LP',
  GET_BALANCER_LP: 'GET_BALANCER_LP',
  GET_BALANCER_LP_TOT: 'GET_BALANCER_LP_TOT',
};
